### ISSUE TITLE
webpackNumbers.numtoword is not a function

### ISSUE THREAD

**Issue by Pettarn** [kalcifer/webpack-library-example#11]
<pre>
require('lodash');
var webpackNumbers = require('./webpack-numbers.js');
var out = function() {
    process.stdout.write('This is the result for numtoword(1) === ' + webpackNumbers.numtoword(1));
};
out();
</pre>

<pre>
TypeError: webpackNumbers.numtoword is not a function
    at out (C:\Node.js\myPlugins\webpack-library-example\example\node\example.js:4:86)
    at Object.<anonymous> (C:\Node.js\myPlugins\webpack-library-example\example\node\example.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
</pre>

**Comment by Pettarn** [comment]
<pre>
{
  "name": "webpack-library-example",
  "version": "1.0.0",
  "description": "",
  "main": "./dist/webpack-numbers.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --mode production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-transform-runtime": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "babel-loader": "^8.0.5",
    "lodash": "^4.17.11",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "@babel/runtime": "^7.4.2"
  }
}

</pre>
<pre>
const path = require('path')
const nodeExternals = require('webpack-node-externals')

module.exports = {
    mode: "production",
    entry: {
        main: "./index.js"
    },
    target: "node",
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "webpack-numbers.js",
        libraryTarget: "umd",
        globalObject: "this",
        library: "webpackNumbers"
    },
    externals: [nodeExternals()],
    module: {
        rules: [
            {
                test: /\.(js)$/,
                exclude: /(node_modules)/,
                use: "babel-loader"
            }
        ]
    }
}
</pre>
<pre>
{
    "presets": [["@babel/preset-env",{
        "targets": {
            "browsers": ["> 1%", "last 2 versions"]
        }
    }]],
    "plugins": ["@babel/plugin-transform-runtime"]    
}
</pre>

**Comment by Pettarn** [comment]
But I copied your bundle file “webpack-numbers.js” into my example / node directory and output the following
<pre>
This is the result for numtoword(1) === One
</pre>

**Comment by Pettarn** [comment]
OK, I know where the problem is ...
